version: "3.3"

services:
  mariadb:
    image: "bitnami/mariadb:10.1"
    network_mode: "bridge"
#    networks:
#      - moodle-net
    environment:
      - MARIADB_USER=user_moodle
      - MARIADB_DATABASE=aqr_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - type: bind
        source: /home/user1/projects/moodle-docker/volume/maria_data
        target: /bitnami
    ports:
      - "3306:3306"
  moodle:
    image: "webdevops/php-apache:7.3"
#    networks:
#      - moodle-net
    network_mode: "bridge"
    environment:
      - MOODLE_DBHOST=mariadb
      - MOODLE_DBPORT=3306
      - MOODLE_DBUSER=bn_moodle
      - MOODLE_DBPASS=''
      - MOODLE_DBNAME=bitnami_moodle
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /home/user1/projects/moodle-docker/volume/moodle_data
        target: /moodledata/moodledata
      - type: bind
        source: /home/user1/projects/moodle-docker/volume/gita-moodle
        target: /app
    depends_on:
      - mariadb

networks:
  moodle-net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
