version: "3.3"

services:
  mysql:
    image: "mysql:5.7"
#    network_mode: "bridge"
    networks:
      - moodle-net
    environment:
      - MYSQL_DATABASE='${DB_DATABASE}'
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ONETIME_PASSWORD=yes
      - MYSQL_USER='${DB_USER}'
      - MYSQL_PASSWORD='${DB_PASSWORD}'
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/log:/var/log/mysql
    ports:
      - ${DB_PORT}:3306
  moodle:
#    image: "webdevops/php-apache:7.3"
    build: .
    #command: service php7.3-fpm start && chmod 777 /run/php/ -R
    networks:
      - moodle-net
#    network_mode: "bridge"
    environment:
      - MOODLE_DBHOST='${DB_HOST}'
      - MOODLE_DBPORT=${DB_PORT}
      - MOODLE_DBUSER='${DB_USER}'
      - MOODLE_DBPASS='${DB_PASSWORD}'
      - MOODLE_DBNAME=moodle
    ports:
      - "${APP_PORT}:80"
      - "${APP_PORT_SSL}:443"
    volumes:
#      - ./volumes/moodle_nginx_config:/etc/nginx/conf.d
#      - ./volumes/moodle_log:/var/log
#      - ./volumes/moodle_php_config:/etc/php/
      - type: bind
        source: ./volumes/moodle_data
        target: /moodledata/moodledata
      - type: bind
        source: ./volumes/gita-moodle
        target: /app
    depends_on:
      - mysql

networks:
  moodle-net:
    driver: bridge

#volumes:
#  mariadb_data:
#    driver: local
#  moodle_data:
#    driver: local
